# Generated by Django 5.0.1 on 2024-03-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sub_сategory',
            new_name='sub_category',
        ),
    ]
